### ISSUE TITLE
Footnote links

### ISSUE THREAD

**Issue by bdolor** [FunnyMonkey/pressbooks#9]
Footnote links in the PDF file don’t currently take you to the footnote area, nor are footnotes parsed. PrinceXML export routine strips out footnote links, but in lieu of stripping the links out it parses footnotes to put them in the footer on the same page where they are declared. mPDF export routine leaves all the footnote links (that go nowhere) and does not parse footnotes to put them on the same page as the declaration. Instead, it puts all footnotes at the end of the content area/chapter/section. I don’t know which behaviour (parsing or resolving the links) will be easier to rectify.

**Comment by jgraham909** [comment]
I don't think we will be able to get footnotes attached to the PDF page they are declared on. That would require far too much additional processing. Right now you add a "page" of content that may turn into multiple PDF pages. In order to get the footnotes attached to the PDF page declared on we would likely need to triple render everything to get the appropriate sizing and offsets matching and then manually split each "page" of content into the appropriate number of pages while adding in appropriate footers. I don't see that as viable given how long the current processing is. Additionally that's a lot of technical debt to incur for such a little gain.

I see the following as viable ways to address this;
1. Accumulating all footnotes across all "pages" and then adding a final footnote page. We could force numeric footnotes, but I'm not sure that the internal linking would work across "pages". There seem to be some weaknesses & shortcomings in how internal links (don't) work.
2. ~~Moving footnotes to the actual footer for the "page" they are added with. This solution would result in each content area (part/chapter) having its own set of footnotes with the footnotes appearing on the last actual page for that part/chapter.~~ This approach is not viable as the footer will apply to all pages that the content spans resulting in repeated footnotes.
3. Applying more styling to the current footnote rendering.

**Comment by bdolor** [comment]
Accumulating footnotes on a final footnote page sounds like converting footnotes into endnotes which won't be ideal especially if internal links are problematic. However, if the shortcomings with internal links aren't too great, the next best thing would be to have the footnotes be placed where they currently are (at the end of the so called mPDF 'page') and have the links to each footnote work? What do you think? I don't know what applying more styling would do, or what you have in mind with that suggestion.

**Comment by jgraham909** [comment]
Based on this it sounds like the only remaining issue is the internal links not working which is already covered in #8 so I will close this and we can track the internal link issue(s) over there.
